spring:
  application:
    name: sale-be
  web:
      resources:
        add-mappings: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Sale;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: false


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method

app:
  cors:
    allowedOrigins: http://localhost:8889,http://localhost:8080


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000